### ISSUE TITLE
php5.6 请求一个不存在的方法 结果返回是成功的

### ISSUE THREAD

**Issue by hpangzi** [walkor/workerman-JsonRpc#4]
请求一个并不存在的方法
结果返回结果还是code为0 msg 为ok
看了下是call_user_func_array 请求一个并不存在的方法的时候会返回一个php waring 
而php waring try catch 是捕捉不到的

**Comment by walkor** [comment]
https://github.com/walkor/workerman-JsonRpc/blob/master/Applications/JsonRpc/start.php#L51
根据源码，当请求的类不存在时，会返回code 404，不是0

**Comment by hpangzi** [comment]
抱歉，可能我描述的不是很清楚，并不是请求一个不存在的类，而是请求一个存在的类下面的不存在的方法，比如说您的demo里面提供了User跟Blog两个类，当我请求User类的getName方法的时候，会返回成功，而不是报错

**Comment by walkor** [comment]
感谢反馈，已经修复
